# Generated by Django 5.1.2 on 2025-08-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("is_looking_for_room", models.BooleanField(default=True)),
                ("bio", models.TextField(blank=True)),
                ("contact_email", models.EmailField(max_length=254)),
                ("halal_kitchen", models.BooleanField(default=True)),
                ("prayer_friendly", models.BooleanField(default=True)),
                ("guests_allowed", models.BooleanField(default=False)),
            ],
        ),
    ]
