# Generated by Django 5.2.5 on 2025-08-14 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("is_looking_for_room", models.BooleanField(default=True)),
                ("bio", models.TextField(blank=True)),
                ("contact_email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("halal_kitchen", models.BooleanField(default=True)),
                ("prayer_friendly", models.BooleanField(default=True)),
                ("guests_allowed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Your name"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Your email"),
                ),
                ("message", models.TextField(verbose_name="Your message")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Contact date"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Has been read"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts_received",
                        to="core.profile",
                        verbose_name="Profile being contacted",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["-created_at"],
            },
        ),
    ]
