# Generated by Django 5.1.2 on 2025-09-18 22:40

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Amenity Name")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Icon Class"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Amenity",
                "verbose_name_plural": "Amenities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Room Type")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Room Type",
                "verbose_name_plural": "Room Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Full Name")),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Age"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=20,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="City",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="State",
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Neighborhood"
                    ),
                ),
                (
                    "is_looking_for_room",
                    models.BooleanField(default=False, verbose_name="Looking for Room"),
                ),
                (
                    "halal_kitchen",
                    models.BooleanField(
                        default=False, verbose_name="Prefers Halal Kitchen"
                    ),
                ),
                (
                    "prayer_friendly",
                    models.BooleanField(
                        default=False,
                        verbose_name="Prefers Prayer-Friendly Environment",
                    ),
                ),
                (
                    "guests_allowed",
                    models.BooleanField(default=True, verbose_name="Allows Guests"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biography")),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contact Email"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="URL Slug"),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=10,
                        null=True,
                        verbose_name="ZIP Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Message Content")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Sent At"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Is Read")),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="core.profile",
                        verbose_name="Recipient",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="core.profile",
                        verbose_name="Sender",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Contact Name")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Contact Email"),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="core.profile",
                        verbose_name="Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Room Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("private", "Private Room"),
                            ("shared", "Shared Room"),
                            ("entire", "Entire Place"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="City"
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Neighborhood"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monthly Rent"
                    ),
                ),
                (
                    "available_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="Available From"
                    ),
                ),
                (
                    "halal_kitchen",
                    models.BooleanField(default=False, verbose_name="Halal Kitchen"),
                ),
                (
                    "prayer_friendly",
                    models.BooleanField(default=False, verbose_name="Prayer-Friendly"),
                ),
                (
                    "guests_allowed",
                    models.BooleanField(default=True, verbose_name="Guests Allowed"),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="URL Slug"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contact Email"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active Listing"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True, to="core.amenity", verbose_name="Amenities"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="core.profile",
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.amenity",
                        verbose_name="Amenity",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.room",
                        verbose_name="Room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Amenity",
                "verbose_name_plural": "Room Amenities",
            },
        ),
        migrations.CreateModel(
            name="RoomAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.room",
                        verbose_name="Room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Availability",
                "verbose_name_plural": "Room Availabilities",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="RoomFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.room",
                        verbose_name="Room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Favorite",
                "verbose_name_plural": "Room Favorites",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload an image (max 5MB, JPEG/PNG/WEBP)",
                        upload_to="room_images/",
                        validators=[
                            core.models.validate_image_size,
                            core.models.validate_image_format,
                        ],
                        verbose_name="Image",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary Image"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Caption"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.room",
                        verbose_name="Room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Image",
                "verbose_name_plural": "Room Images",
                "ordering": ["-is_primary", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoommateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "budget",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Monthly Budget"
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Occupation"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roommate_profile",
                        to="core.profile",
                        verbose_name="Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Roommate Profile",
                "verbose_name_plural": "Roommate Profiles",
            },
        ),
        migrations.CreateModel(
            name="RoomReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Comment")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.profile",
                        verbose_name="Reviewer",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.room",
                        verbose_name="Room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Review",
                "verbose_name_plural": "Room Reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Is Verified"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified At"
                    ),
                ),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.room",
                        verbose_name="Room",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Verification",
                "verbose_name_plural": "Room Verifications",
            },
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["city", "state"], name="core_profil_city_5a36c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["is_looking_for_room"], name="core_profil_is_look_970fd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["gender"], name="core_profil_gender_2b6106_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["city", "neighborhood"], name="core_room_city_de8e2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["price"], name="core_room_price_092ba3_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["available_from"], name="core_room_availab_eb64bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["is_active"], name="core_room_is_acti_9de2db_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roomamenity",
            unique_together={("room", "amenity")},
        ),
        migrations.AlterUniqueTogether(
            name="roomfavorite",
            unique_together={("user", "room")},
        ),
        migrations.AlterUniqueTogether(
            name="roomreview",
            unique_together={("room", "reviewer")},
        ),
    ]
