# Generated by Django 5.1.2 on 2025-08-07 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(max_length=100, verbose_name="Your name"),
                ),
                (
                    "sender_email",
                    models.EmailField(max_length=254, verbose_name="Your email"),
                ),
                ("message", models.TextField(verbose_name="Your message")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Contact date"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Has been read"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts_received",
                        to="core.profile",
                        verbose_name="Profile being contacted",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["-created_at"],
            },
        ),
    ]
