# Generated by Django 5.1.2 on 2025-09-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="available_from",
            field=models.DateField(blank=True, null=True),
        ),
    ]
