# Generated by Django 5.1.2 on 2025-09-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="amenity",
            name="slug",
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Amenity Name"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="amenities",
            field=models.ManyToManyField(
                blank=True,
                related_name="rooms",
                to="core.amenity",
                verbose_name="Amenities",
            ),
        ),
    ]
