# Generated by Django 5.1.2 on 2025-08-26 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("city", models.CharField(max_length=100)),
                (
                    "neighborhood",
                    models.CharField(
                        blank=True,
                        help_text="Downtown, West Ashley, Mount Pleasant",
                        max_length=100,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("available_from", models.DateField(blank=True, null=True)),
                ("halal_kitchen", models.BooleanField(default=True)),
                ("prayer_friendly", models.BooleanField(default=True)),
                ("guests_allowed", models.BooleanField(default=False)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="neighborhood",
            field=models.CharField(
                blank=True,
                help_text="Downtown, West Ashley, Mount Pleasant",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["city", "neighborhood"], name="core_profil_city_aeab0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["age"], name="core_profil_age_b743af_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["gender"], name="core_profil_gender_2b6106_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["city", "gender"], name="core_profil_city_a9ac94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["city", "is_looking_for_room"],
                name="core_profil_city_d68a9c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["city", "halal_kitchen"], name="core_profil_city_a54eec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["city", "prayer_friendly"], name="core_profil_city_4b3abe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["city", "guests_allowed"], name="core_profil_city_f18370_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["is_looking_for_room"], name="core_profil_is_look_970fd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["city", "created_at"], name="core_profil_city_08fb0a_idx"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rooms",
                to="core.profile",
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["city", "neighborhood"], name="core_room_city_de8e2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["city", "created_at"], name="core_room_city_38e0c3_idx"
            ),
        ),
    ]
