# Generated by Django 5.1.2 on 2025-09-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_amenity_slug_alter_amenity_name_alter_room_amenities"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="default_amenities",
            field=models.ManyToManyField(blank=True, to="core.amenity"),
        ),
    ]
