# Generated by Django 5.1.2 on 2025-09-17 00:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_profile_state_profile_zip_code_alter_profile_city"),
    ]

    operations = []
