# Generated by Django 5.1.2 on 2025-09-01 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_amenity_roomtype_profile_user_room_furnished_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="user",
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="RoommateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prays_five_times", models.BooleanField(default=True)),
                ("goes_to_masjid", models.BooleanField(default=True)),
                ("halal_only", models.BooleanField(default=True)),
                (
                    "cleanliness_level",
                    models.CharField(
                        choices=[
                            ("very_clean", "Very Clean"),
                            ("average", "Average"),
                            ("messy", "Messy"),
                        ],
                        default="average",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roommate_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
