# Generated by Django 5.1.2 on 2025-09-22 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_roomtype_default_amenities"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roomtype",
            name="default_amenities",
        ),
        migrations.AlterField(
            model_name="amenity",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Amenity Name"),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="amenities",
            field=models.ManyToManyField(
                blank=True, to="core.amenity", verbose_name="Amenities"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.roomtype",
                verbose_name="Room Type",
            ),
        ),
    ]
