# Generated by Django 5.1.2 on 2025-08-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_profile_options_profile_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
    ]
