# Generated by Django 5.1.2 on 2025-09-17 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_auto_20250916_2036"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={
                "ordering": ["name"],
                "verbose_name": "Amenity",
                "verbose_name_plural": "Amenities",
            },
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
        migrations.AlterModelOptions(
            name="roomamenity",
            options={
                "verbose_name": "Room Amenity",
                "verbose_name_plural": "Room Amenities",
            },
        ),
        migrations.AlterModelOptions(
            name="roomavailability",
            options={
                "ordering": ["start_date"],
                "verbose_name": "Room Availability",
                "verbose_name_plural": "Room Availabilities",
            },
        ),
        migrations.AlterModelOptions(
            name="roomfavorite",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Room Favorite",
                "verbose_name_plural": "Room Favorites",
            },
        ),
        migrations.AlterModelOptions(
            name="roomimage",
            options={
                "ordering": ["-is_primary", "created_at"],
                "verbose_name": "Room Image",
                "verbose_name_plural": "Room Images",
            },
        ),
        migrations.AlterModelOptions(
            name="roommateprofile",
            options={
                "verbose_name": "Roommate Profile",
                "verbose_name_plural": "Roommate Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="roomreview",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Room Review",
                "verbose_name_plural": "Room Reviews",
            },
        ),
        migrations.AlterModelOptions(
            name="roomtype",
            options={
                "ordering": ["name"],
                "verbose_name": "Room Type",
                "verbose_name_plural": "Room Types",
            },
        ),
        migrations.AlterModelOptions(
            name="roomverification",
            options={
                "verbose_name": "Room Verification",
                "verbose_name_plural": "Room Verifications",
            },
        ),
        migrations.AddField(
            model_name="amenity",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="amenity",
            name="icon",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Icon Class"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="Is Read"),
        ),
        migrations.AddField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created At"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated At"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created At"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active Listing"),
        ),
        migrations.AddField(
            model_name="room",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated At"
            ),
        ),
        migrations.AddField(
            model_name="roomimage",
            name="caption",
            field=models.CharField(blank=True, max_length=200, verbose_name="Caption"),
        ),
        migrations.AddField(
            model_name="roomimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created At"
            ),
        ),
        migrations.AddField(
            model_name="roommateprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created At"
            ),
        ),
        migrations.AddField(
            model_name="roomreview",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated At"
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="roomverification",
            name="verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Verified At"
            ),
        ),
        migrations.AddField(
            model_name="roomverification",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Verified By",
            ),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Amenity Name"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Contact Email"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Contact Name"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="core.profile",
                verbose_name="Profile",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(verbose_name="Message Content"),
        ),
        migrations.AlterField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to="core.profile",
                verbose_name="Recipient",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to="core.profile",
                verbose_name="Sender",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Sent At"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Age"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Biography"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Contact Email"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                max_length=20,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="guests_allowed",
            field=models.BooleanField(default=True, verbose_name="Allows Guests"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="halal_kitchen",
            field=models.BooleanField(
                default=False, verbose_name="Prefers Halal Kitchen"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_looking_for_room",
            field=models.BooleanField(default=False, verbose_name="Looking for Room"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="neighborhood",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Neighborhood"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="prayer_friendly",
            field=models.BooleanField(
                default=False, verbose_name="Prefers Prayer-Friendly Environment"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="URL Slug"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="state",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User Account",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="zip_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=10,
                null=True,
                verbose_name="ZIP Code",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="amenities",
            field=models.ManyToManyField(
                blank=True, to="core.amenity", verbose_name="Amenities"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="available_from",
            field=models.DateField(
                blank=True, null=True, verbose_name="Available From"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="city",
            field=models.CharField(db_index=True, max_length=100, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="room",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Contact Email"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="room",
            name="guests_allowed",
            field=models.BooleanField(default=True, verbose_name="Guests Allowed"),
        ),
        migrations.AlterField(
            model_name="room",
            name="halal_kitchen",
            field=models.BooleanField(default=False, verbose_name="Halal Kitchen"),
        ),
        migrations.AlterField(
            model_name="room",
            name="neighborhood",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Neighborhood"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="prayer_friendly",
            field=models.BooleanField(default=False, verbose_name="Prayer-Friendly"),
        ),
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Monthly Rent"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.roomtype",
                verbose_name="Room Type",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="URL Slug"),
        ),
        migrations.AlterField(
            model_name="room",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Room Title"),
        ),
        migrations.AlterField(
            model_name="room",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="core.profile",
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="roomamenity",
            name="amenity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.amenity",
                verbose_name="Amenity",
            ),
        ),
        migrations.AlterField(
            model_name="roomamenity",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.room",
                verbose_name="Room",
            ),
        ),
        migrations.AlterField(
            model_name="roomavailability",
            name="end_date",
            field=models.DateField(verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="roomavailability",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.room",
                verbose_name="Room",
            ),
        ),
        migrations.AlterField(
            model_name="roomavailability",
            name="start_date",
            field=models.DateField(verbose_name="Start Date"),
        ),
        migrations.AlterField(
            model_name="roomfavorite",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="roomfavorite",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.room",
                verbose_name="Room",
            ),
        ),
        migrations.AlterField(
            model_name="roomfavorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="roomimage",
            name="image",
            field=models.ImageField(upload_to="room_images/", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="roomimage",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="Primary Image"),
        ),
        migrations.AlterField(
            model_name="roomimage",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="core.room",
                verbose_name="Room",
            ),
        ),
        migrations.AlterField(
            model_name="roommateprofile",
            name="budget",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Monthly Budget"
            ),
        ),
        migrations.AlterField(
            model_name="roommateprofile",
            name="occupation",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Occupation"
            ),
        ),
        migrations.AlterField(
            model_name="roommateprofile",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roommate_profile",
                to="core.profile",
                verbose_name="Profile",
            ),
        ),
        migrations.AlterField(
            model_name="roomreview",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="roomreview",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="roomreview",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1 Star"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ],
                verbose_name="Rating",
            ),
        ),
        migrations.AlterField(
            model_name="roomreview",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.profile",
                verbose_name="Reviewer",
            ),
        ),
        migrations.AlterField(
            model_name="roomreview",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="core.room",
                verbose_name="Room",
            ),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Room Type"),
        ),
        migrations.AlterField(
            model_name="roomverification",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Is Verified"),
        ),
        migrations.AlterField(
            model_name="roomverification",
            name="room",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.room",
                verbose_name="Room",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roomamenity",
            unique_together={("room", "amenity")},
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["city", "state"], name="core_profil_city_5a36c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["is_looking_for_room"], name="core_profil_is_look_970fd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["gender"], name="core_profil_gender_2b6106_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["city", "neighborhood"], name="core_room_city_de8e2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["price"], name="core_room_price_092ba3_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["available_from"], name="core_room_availab_eb64bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["is_active"], name="core_room_is_acti_9de2db_idx"
            ),
        ),
    ]
