# Generated by Django 5.1.2 on 2025-09-17 00:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_amenity_options_alter_contact_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomimage",
            name="image",
            field=models.ImageField(
                help_text="Upload an image (max 5MB, JPEG/PNG/WEBP)",
                upload_to="room_images/",
                validators=[
                    core.models.validate_image_size,
                    core.models.validate_image_format,
                ],
                verbose_name="Image",
            ),
        ),
    ]
