# Generated by Django 5.1.2 on 2025-09-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_roomtype_default_amenities_alter_amenity_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenity",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
